# Generated by Django 6.0.4 on 2026-04-27 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_department_alter_user_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("head", "Руководитель отдела"),
                            ("member", "Сотрудник"),
                        ],
                        default="member",
                        max_length=10,
                        verbose_name="Роль в отделе",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Назначен"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначил",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="users.department",
                        verbose_name="Отдел",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Членство в отделе",
                "verbose_name_plural": "Членства в отделах",
                "ordering": ["department", "role"],
                "unique_together": {("user", "department")},
            },
        ),
    ]
