# Generated by Django 4.2.30 on 2026-04-20 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('login_failed', 'Неудачная попытка входа'), ('file_upload', 'Загрузка файла'), ('file_download', 'Скачивание файла'), ('file_delete', 'Удаление файла'), ('file_view', 'Просмотр файла'), ('user_create', 'Создание пользователя'), ('user_update', 'Изменение пользователя'), ('access_denied', 'Отказ в доступе')], max_length=30, verbose_name='Действие')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='Тип объекта')),
                ('object_id', models.CharField(blank=True, max_length=255, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Представление объекта')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Дополнительно')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ['-timestamp'],
            },
        ),
    ]
