# Generated by Django 4.2.30 on 2026-04-20 03:16

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=255, verbose_name='Оригинальное имя')),
                ('encrypted_file', models.FileField(upload_to=files.models.upload_to, verbose_name='Файл (зашифрован)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME-тип')),
                ('size', models.PositiveBigIntegerField(verbose_name='Размер (байт)')),
                ('checksum', models.CharField(max_length=64, verbose_name='SHA-256 контрольная сумма')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('deleted', 'Удалён')], default='active', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FilePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.CharField(choices=[('read', 'Чтение'), ('download', 'Скачивание')], default='read', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.file')),
            ],
            options={
                'verbose_name': 'Право доступа',
                'verbose_name_plural': 'Права доступа',
            },
        ),
    ]
