# Generated by Django 6.0.4 on 2026-04-23 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("users", "0002_department_alter_user_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Название"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="file_categories",
                        to="users.department",
                        verbose_name="Разрешённые отделы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория файлов",
                "verbose_name_plural": "Категории файлов",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="files.filecategory",
                verbose_name="Категория",
            ),
        ),
    ]
