# Generated by Django 6.0.4 on 2026-04-28 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_alter_file_options_folder_file_folder"),
        ("users", "0003_departmentmembership"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="category",
        ),
        migrations.AlterField(
            model_name="folder",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folders",
                to="users.department",
                verbose_name="Отдел",
            ),
        ),
        migrations.DeleteModel(
            name="FileCategory",
        ),
    ]
