# Generated by Django 6.0.4 on 2026-05-14 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_remove_file_category_alter_folder_department_and_more'),
        ('users', '0005_split_admin_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_role', models.CharField(blank=True, choices=[('head', 'Руководитель отдела'), ('member', 'Сотрудник')], max_length=10, verbose_name='Роль в отделе')),
                ('access', models.CharField(choices=[('view', 'Просмотр в списке'), ('read', 'Чтение'), ('download', 'Скачивание'), ('upload', 'Загрузка'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('share', 'Передача доступа'), ('manage', 'Управление'), ('audit', 'Просмотр аудита')], default='read', max_length=20, verbose_name='Действие')),
                ('effect', models.CharField(choices=[('allow', 'Разрешить'), ('deny', 'Запретить')], default='allow', max_length=10, verbose_name='Эффект')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
            ],
            options={
                'verbose_name': 'Право доступа к папке',
                'verbose_name_plural': 'Права доступа к папкам',
            },
        ),
        migrations.AlterModelOptions(
            name='filepermission',
            options={'verbose_name': 'Право доступа к файлу', 'verbose_name_plural': 'Права доступа к файлам'},
        ),
        migrations.AlterUniqueTogether(
            name='filepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_permissions', to='users.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='department_role',
            field=models.CharField(blank=True, choices=[('head', 'Руководитель отдела'), ('member', 'Сотрудник')], max_length=10, verbose_name='Роль в отделе'),
        ),
        migrations.AddField(
            model_name='filepermission',
            name='effect',
            field=models.CharField(choices=[('allow', 'Разрешить'), ('deny', 'Запретить')], default='allow', max_length=10, verbose_name='Эффект'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='access',
            field=models.CharField(choices=[('view', 'Просмотр в списке'), ('read', 'Чтение'), ('download', 'Скачивание'), ('upload', 'Загрузка'), ('create', 'Создание'), ('update', 'Изменение'), ('delete', 'Удаление'), ('share', 'Передача доступа'), ('manage', 'Управление'), ('audit', 'Просмотр аудита')], default='read', max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.file', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Выдано'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_%(class)s_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Выдал'),
        ),
        migrations.AlterField(
            model_name='filepermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='filepermission',
            constraint=models.CheckConstraint(condition=(models.Q(('department__isnull', True), ('department_role', ''), ('user__isnull', False)) | models.Q(('department__isnull', False), ('user__isnull', True))), name='file_permission_has_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='filepermission',
            constraint=models.UniqueConstraint(fields=('file', 'user', 'access'), name='unique_file_user_access'),
        ),
        migrations.AddConstraint(
            model_name='filepermission',
            constraint=models.UniqueConstraint(fields=('file', 'department', 'department_role', 'access'), name='unique_file_department_role_access'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_permissions', to='users.department', verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='files.folder', verbose_name='Папка'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_%(class)s_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Выдал'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.CheckConstraint(condition=(models.Q(('department__isnull', True), ('department_role', ''), ('user__isnull', False)) | models.Q(('department__isnull', False), ('user__isnull', True))), name='folder_permission_has_one_subject'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(fields=('folder', 'user', 'access'), name='unique_folder_user_access'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(fields=('folder', 'department', 'department_role', 'access'), name='unique_folder_department_role_access'),
        ),
    ]
